---
abstract: 'OO Interface to Instagram REST API'
author:
  - 'Gabriel Vieira <gabriel.vieira@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: API-Instagram
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  Moo: 0
  Time::Moment: 0
  URI: 0
  constant: 0
  strict: 0
  warnings: 0
version: 0.002
